const dataArray = [
    {
        letter: 'א',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Alef_%28Rashi-script_-_Hebrew_letter%29.svg/800px-Alef_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ב',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Bet_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Bet_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ג',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Gimel_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Gimel_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ד',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Daled_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Daled_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ה',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/He_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-He_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ו',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Vav_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Vav_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ז',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Zayin_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Zayin_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ח',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Het_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Het_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ט',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Tet_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Tet_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'י',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Yud_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Yud_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'כ',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Kaf-nonfinal_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Kaf-nonfinal_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ך',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Kaf-final_%28Rashi-script_-_Hebrew_letter%29.svg/800px-Kaf-final_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ל',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Lamed_%28Rashi-script_-_Hebrew_letter%29.svg/800px-Lamed_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'מ',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Mem-nonfinal_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Mem-nonfinal_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ם',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Mem-final_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Mem-final_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'נ',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Nun-nonfinal_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Nun-nonfinal_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ן',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Nun-final_%28Rashi-script_-_Hebrew_letter%29.svg/800px-Nun-final_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ס',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Samekh_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Samekh_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ע',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Ayin_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Ayin_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'פ',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pe-nonfinal_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Pe-nonfinal_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ף',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Pe-final_%28Rashi-script_-_Hebrew_letter%29.svg/800px-Pe-final_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'צ',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Tsadik-nonfinal_%28Rashi-script_-_Hebrew_letter%29.svg/800px-Tsadik-nonfinal_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ץ',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Tsadik-final_%28Rashi-script_-_Hebrew_letter%29.svg/800px-Tsadik-final_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ק',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Kuf_%28Rashi-script_-_Hebrew_letter%29.svg/800px-Kuf_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ר',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Resh_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Resh_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ש',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Shin_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Shin_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    },
    {
        letter:'ת',
        imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Taf_%28Rashi-script_-_Hebrew_letter%29.svg/1024px-Taf_%28Rashi-script_-_Hebrew_letter%29.svg.png'
    }
]
export default dataArray
